name: Install Tools & Dependencies
description: Installs pnpm, Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm (corepack enabled)
      uses: pnpm/action-setup@v3

    - name: Setup Node.js 20.x
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: 20.10
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm ci:install
      shell: bash